<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logoff">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$_SESSION['name']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalTweets['totalTweets']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalFollowing['totalFollowing']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->totalFollowers['totalFollowers']?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach($this->view->tweets as $id_tweet => $tweet)
                { ?>
                    <div class="row tweet">
                        <div class="col">
                            <p><strong><?=$tweet['name'] ?></strong> <small><span class="text text-muted">- <?=$tweet['data'] ?> </span></small></p>
                            <p><?=$tweet['tweet'] ?></p>

                            <br />
							<?php if($tweet['id_user'] == $_SESSION['id'])
							{ ?>
                            <form method="post" action="/deleteTweet?id_tweet=<?=$tweet['id']?>"> 
                                <div class="col d-flex justify-content-end">
                                    <button type="submit" class="btn btn-danger"><small>Remover</small></button>
                                </div>
                            </form>	
							<?php } ?>	
                        </div>
                    </div>
                <?php } ?>
				<div class="row mt-5">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item ">
							<a class="page-link" href="?page=1" tabindex="-1">Primeiro</a>
						</li>
						<li class="page-item ">
						<a class="page-link" href="?page=<?=$this->view->pageOn-1?>" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
							<span class="sr-only">Previous</span>
						</a>
						</li>
						<?php for($i = 1; $i <= $this->view->total_page; $i++ ) { ?>
							<li class="page-item <?=$this->view->pageOn == $i ? 'active' : '' ?>">
								<a class="page-link "  href="?page=<?=$i?>"><?=$i?></a>
							</li>
						<?php } ?>
						<a class="page-link" href="?page=<?=$this->view->pageOn+1?>" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						<a class="page-link" href="?page<?=$this->view->total_page?>">Ultimo</a>
						</li>
					</ul>
				</nav>
				</div>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/whoToFollow" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>